import { IProject } from "@/interfaces/project.interface";

export const PROJECTS: IProject[] = [
  {
    name: 'Portfolio',
    client: 'NG',
    summary: 'Personal website rebuilt with Next.js to present experience, projects and contact flow in a cleaner product format.',
    stack: ['Next.js', 'TypeScript', 'SCSS', 'Resend'],
    href: 'https://portfolio.gomesnicolas.com/',
    status: 'live',
  },
  {
    name: 'Design My Bic',
    client: 'BIC',
    summary: 'Customization experience for BIC products, combining front-end polish and client-facing delivery constraints.',
    stack: ['Vue.js', 'TypeScript', 'Node.js'],
    href: 'https://us.bic.com/en_us/design-my-bic-lighters-set-of-6-personalized-lighters.html',
    status: 'case-study',
  },
  {
    name: 'Voodoo Blog',
    client: 'Voodoo',
    summary: 'Content platform work for a high-traffic gaming brand with emphasis on maintainability and delivery speed.',
    stack: ['React', 'Node.js', 'Contentful'],
    status: 'case-study',
  },
  {
    name: 'Monster Playable',
    client: 'YSO Corp',
    summary: 'Interactive playable ad workflow involving rapid iteration, performance constraints and cross-team delivery.',
    stack: ['JavaScript', 'Canvas', 'Webpack'],
    status: 'private',
  },
  {
    name: 'YSO Network',
    client: 'YSO Corp',
    summary: 'Internal platform and tooling work to support product operations and collaboration across teams.',
    stack: ['Nuxt.js', 'Node.js', 'PostgreSQL'],
    status: 'private',
  },
  {
    name: 'GameUtils',
    client: 'YSO Corp',
    summary: 'Developer tooling and utilities designed to speed up production workflows and repeated delivery tasks.',
    stack: ['Node.js', 'TypeScript', 'Shell'],
    href: 'https://gameutils.ysocorp.com',
    status: 'private',
  },
  {
    name: 'Sartliva',
    client: 'YSO Corp',
    summary: 'Custom product development for a client project with full-stack ownership and iterative delivery.',
    stack: ['React', 'Koa', 'PostgreSQL'],
    status: 'private',
  },
  {
    name: 'Hit The Road',
    client: 'LCE',
    summary: 'Client-facing product work blending application features, business constraints and delivery ownership.',
    stack: ['Angular', 'Node.js', 'MySQL'],
    status: 'private',
  },
  {
    name: 'InovoiZ',
    client: 'InovoiZ',
    summary: 'Product contribution on a business-oriented platform, with focus on usable interfaces and robust integrations.',
    stack: ['React', 'TypeScript', 'API integrations'],
    status: 'private',
  },
];
